-- Create Inventory Table
create table if not exists inventory (
  id bigint generated by default as identity primary key,
  name text not null,
  quantity float default 1,
  unit text default '개',
  category text default '기타',
  purchase_date date,
  expiry_date date,
  confidence float,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table inventory enable row level security;

-- Create Policy to allow all access (since we are using service key/api key in environment)
-- Note: In production, you would restrict this to authenticated users.
create policy "Allow all access" on inventory for all using (true) with check (true);
